env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64

upx:
  - enabled: true
    compress: best

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

release:
  footer: |
    Full Changelog: [{{ .PreviousTag }}...{{ .Tag }}](https://{{ .ModulePath }}/compare/{{ .PreviousTag }}...{{ .Tag }})

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: '🚀 Features'
      regexp: 'feat:'
    - title: '🐛 Bug Fixes'
      regexp: 'fix:'
    - title: '🔨 Others'
