name: "build-image"

on:
  push:
    tags:
      - '*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish image
        uses: xiaoxuan6/docker-build-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extract-git-tag: true
          image-platform: linux/arm64,linux/amd64

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
